In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
import sys
sys.path.append("/Users/ejowik001/Desktop/Github/Nowcasting/kedro/refinery/dependencies/")
# from utils import cast_spec_to_dict
from load_spec import load_spec
from load_data import load_data
# from retransform_data import retransform_data
from retransform_prediction import retransform_

In [3]:
pd.set_option("display.max_columns", None)
# np.set_printoptions(threshold=sys.maxsize)

In [4]:
ds = pd.read_excel("harmonized_time_series.xlsx", header=None)

In [5]:
# ds_spec = pd.read_csv("../data/02_intermediate/variable.csv")
# Spec = cast_spec_to_dict(ds_spec)
Spec = load_spec("Spec_US_test.xls")

Table 1: Model specification
              SeriesID                   SeriesName                 Units  \
0               PAYEMS           Payroll Employment  Thousands of Persons
1               JTSJOL                 Job Openings             Thousands
2             CPIAUCSL         Consumer Price Index                 Index
3              DGORDER         Durable Goods Orders           $, Millions
4                RSAFS                 Retail Sales           $, Millions
5               UNRATE            Unemployment Rate                     %
6                HOUST               Housing Starts    Thousands of Units
7               INDPRO        Industrial Production                 Index
8              DSPIC96              Personal Income   Chained $, Billions
9              BOPTEXP                      Exports           $, Millions
10             BOPTIMP                      Imports           $, Millions
11             TTLCONS        Construction Spending           $, Millions
12                  IR           Import Price Index                 Index
13            CPILFESL    Core Consumer Price Index                 Index
14            PCEPILFE         Core PCE Price Index                 Index
15               PCEPI              PCE Price Index                 Index
16              PERMIT             Building Permits    Thousands of Units
17                 TCU    Capacity Utilization Rate                     %
18              BUSINV         Business Inventories           $, Millions
19                  IQ           Export Price Index                 Index
20   GACDISA066MSFRBNY       Empire State Mfg Index                 Index
21              PCEC96    Real Consumption Spending   Chained $, Billions
22  GACDFSA066MSFRBPHI   Philadelphia Fed Mfg Index                 Index
23               GDPC1  Real Gross Domestic Product   Chained $, Billions
24              ULCNFB              Unit Labor Cost                 Index

                        Transformation
0                  Change (Difference)
1                  Change (Difference)
2                       Percent Change
3                       Percent Change
4                       Percent Change
5                  Change (Difference)
6                       Percent Change
7        Year over Year Percent Change
8                       Percent Change
9        Year over Year Percent Change
10        Percent Change (Annual Rate)
11                      Percent Change
12                      Percent Change
13                      Percent Change
14                      Percent Change
15                      Percent Change
16                 Change (Difference)
17                 Change (Difference)
18                      Percent Change
19                      Percent Change
20          Levels (No Transformation)
21                      Percent Change
22          Levels (No Transformation)
23       Year over Year Percent Change
24  Year over Year Change (Difference)

/Users/ejowik001/Desktop/Github/Nowcasting/kedro/refinery/dependencies/load_spec.py:41: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  blocks = raw_data[block_cols].fillna(0).astype(int).values

In [11]:
sample_start = "2000-01-01"
sample_start = pd.to_datetime(sample_start, format="%Y-%m-%d")

test = ds[np.where(ds.loc[0].isin(["ReferenceDate"]+list(Spec["seriesid"])))[0]]
X, Time, Z, header = load_data(test, Spec)
df = pd.DataFrame(X, columns=header, index=Time)
df

Loading data...

,PAYEMS,JTSJOL,CPIAUCSL,DGORDER,RSAFS,UNRATE,HOUST,INDPRO,DSPIC96,BOPTEXP,BOPTIMP,TTLCONS,IR,CPILFESL,PCEPILFE,PCEPI,PERMIT,TCU,BUSINV,IQ,GACDISA066MSFRBNY,PCEC96,GACDFSA066MSFRBPHI,GDPC1,ULCNFB
1855-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-01,108.0,-458.0,0.312910,0.797170,-0.150198,0.1,6.004619,-0.751956,0.159196,1.467434,-19.002488,0.094716,0.854093,0.291761,0.334092,0.339144,-45.0,-0.1192,-0.128033,0.672043,-14.3,-0.025495,15.5,3.036849,0.408
2024-05-01,216.0,-436.0,0.005747,0.227228,0.231684,0.1,-4.502542,0.227906,-0.059678,4.521728,36.164004,1.283284,-0.141143,0.163087,0.254873,0.261439,-41.0,0.5152,0.344159,-0.734312,-15.6,0.532973,4.5,NaN,NaN
2024-06-01,118.0,311.0,-0.056190,0.088421,-0.278145,0.1,1.064639,0.877996,0.325762,3.950096,-3.916990,0.232621,0.000000,0.064751,0.101690,0.007311,55.0,-0.0222,0.495008,-0.201748,-6.0,0.263171,1.3,NaN,NaN
2024-07-01,89.0,-320.0,0.154928,-6.871694,1.147434,0.2,-6.922498,-0.743556,0.086038,5.655462,8.090257,0.035928,0.212014,0.165229,0.163031,0.060920,-48.0,-0.8126,0.277588,0.539084,-6.6,0.376960,13.9,NaN,NaN
2024-08-01,142.0,-237.0,0.187221,9.832626,0.051238,-0.1,9.620049,0.042485,0.106572,4.993640,28.360320,-0.290781,-0.282087,0.280990,0.161129,0.155049,64.0,0.5493,0.350477,-0.670241,-4.7,1.382457,-7.0,NaN,NaN

In [12]:
sample_start = "2000-01-01"
sample_start = pd.to_datetime(sample_start, format="%Y-%m-%d")

X, Time, Z, header = load_data(test, Spec, sample_start)

Loading data...

In [13]:
R = retransform_(X, Z, Time, Spec, header, datetime(2023, 1, 1))
R_df = pd.DataFrame(R, columns=header, index=Time)

Z_df = pd.DataFrame(Z, columns=header, index=Time)

In [14]:
R_df

,PAYEMS,JTSJOL,CPIAUCSL,DGORDER,RSAFS,UNRATE,HOUST,INDPRO,DSPIC96,BOPTEXP,BOPTIMP,TTLCONS,IR,CPILFESL,PCEPILFE,PCEPI,PERMIT,TCU,BUSINV,IQ,GACDISA066MSFRBNY,PCEC96,GACDFSA066MSFRBPHI,GDPC1,ULCNFB
2000-01-01,131009.0,NaN,169.300,196344.0,268044.0,4.0,1636.0,91.4092,9735.9,86192.0,112131.0,789431.0,97.8,179.300,74.128,72.763,1727.0,82.0932,1137260.0,99.2,NaN,7988.5,11.3,13878.147,85.710
2000-02-01,131120.0,NaN,170.000,201360.0,272020.0,4.1,1737.0,91.7245,9799.9,86001.0,113133.0,784940.0,99.7,179.400,74.306,72.961,1692.0,82.0943,1140023.0,99.6,NaN,8065.3,14.5,NaN,NaN
2000-03-01,131604.0,NaN,171.000,183911.0,275192.0,4.0,1604.0,92.0830,9837.9,86540.0,116334.0,793737.0,99.9,180.000,74.415,73.191,1651.0,82.1340,1146435.0,100.0,NaN,8110.8,19.4,NaN,NaN
2000-04-01,131883.0,NaN,170.900,192130.0,271046.0,3.8,1626.0,92.6659,9864.0,88115.0,118672.0,809459.0,98.5,180.300,74.568,73.505,1597.0,82.3741,1150666.0,100.0,NaN,8101.6,10.0,14130.908,84.232
2000-05-01,132106.0,NaN,171.200,195044.0,271394.0,4.0,1575.0,92.9347,9913.7,89359.0,117957.0,804766.0,98.8,180.700,74.617,73.444,1543.0,82.3350,1157552.0,100.2,NaN,8139.0,13.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-01,158214.0,8355.0,313.207,282096.0,702681.0,3.9,1377.0,102.4479,16924.3,260681.0,328653.0,2135771.0,141.7,317.622,121.629,122.782,1440.0,77.7263,2537490.0,149.8,-14.3,15685.6,15.5,23223.906,120.245
2024-05-01,158430.0,7919.0,313.225,282737.0,704309.0,4.0,1315.0,103.2156,16914.2,262314.0,337217.0,2163179.0,141.5,318.140,121.939,123.103,1399.0,78.2415,2546223.0,148.7,-15.6,15769.2,4.5,NaN,NaN
2024-06-01,158548.0,8230.0,313.049,282987.0,702350.0,4.1,1329.0,103.2798,16969.3,260790.0,336096.0,2168211.0,141.5,318.346,122.063,123.112,1454.0,78.2193,2558827.0,148.4,-6.0,15810.7,1.3,NaN,NaN
2024-07-01,158637.0,7910.0,313.534,263541.0,710409.0,4.3,1237.0,102.3058,16983.9,265266.0,338282.0,2168990.0,141.8,318.872,122.262,123.187,1406.0,77.4067,2565930.0,149.2,-6.6,15870.3,13.9,NaN,NaN
2024-08-01,158779.0,7673.0,314.121,289454.0,710773.0,4.2,1356.0,103.1389,17002.0,266603.0,345394.0,2162683.0,141.4,319.768,122.459,123.378,1470.0,77.9560,2574923.0,148.2,-4.7,16089.7,-7.0,NaN,NaN

In [15]:
Z_df

,PAYEMS,JTSJOL,CPIAUCSL,DGORDER,RSAFS,UNRATE,HOUST,INDPRO,DSPIC96,BOPTEXP,BOPTIMP,TTLCONS,IR,CPILFESL,PCEPILFE,PCEPI,PERMIT,TCU,BUSINV,IQ,GACDISA066MSFRBNY,PCEC96,GACDFSA066MSFRBPHI,GDPC1,ULCNFB
2000-01-01,131009.0,NaN,169.300,196344.0,268044.0,4.0,1636.0,91.4092,9735.9,86192.0,112131.0,789431.0,97.8,179.300,74.128,72.763,1727.0,82.0932,1137260.0,99.2,NaN,7988.5,11.3,13878.147,85.710
2000-02-01,131120.0,NaN,170.000,201360.0,272020.0,4.1,1737.0,91.7245,9799.9,86001.0,113133.0,784940.0,99.7,179.400,74.306,72.961,1692.0,82.0943,1140023.0,99.6,NaN,8065.3,14.5,NaN,NaN
2000-03-01,131604.0,NaN,171.000,183911.0,275192.0,4.0,1604.0,92.0830,9837.9,86540.0,116334.0,793737.0,99.9,180.000,74.415,73.191,1651.0,82.1340,1146435.0,100.0,NaN,8110.8,19.4,NaN,NaN
2000-04-01,131883.0,NaN,170.900,192130.0,271046.0,3.8,1626.0,92.6659,9864.0,88115.0,118672.0,809459.0,98.5,180.300,74.568,73.505,1597.0,82.3741,1150666.0,100.0,NaN,8101.6,10.0,14130.908,84.232
2000-05-01,132106.0,NaN,171.200,195044.0,271394.0,4.0,1575.0,92.9347,9913.7,89359.0,117957.0,804766.0,98.8,180.700,74.617,73.444,1543.0,82.3350,1157552.0,100.2,NaN,8139.0,13.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-01,158214.0,8355.0,313.207,282096.0,702681.0,3.9,1377.0,102.4479,16924.3,260681.0,328653.0,2135771.0,141.7,317.622,121.629,122.782,1440.0,77.7263,2537490.0,149.8,-14.3,15685.6,15.5,23223.906,120.245
2024-05-01,158430.0,7919.0,313.225,282737.0,704309.0,4.0,1315.0,103.2156,16914.2,262314.0,337217.0,2163179.0,141.5,318.140,121.939,123.103,1399.0,78.2415,2546223.0,148.7,-15.6,15769.2,4.5,NaN,NaN
2024-06-01,158548.0,8230.0,313.049,282987.0,702350.0,4.1,1329.0,103.2798,16969.3,260790.0,336096.0,2168211.0,141.5,318.346,122.063,123.112,1454.0,78.2193,2558827.0,148.4,-6.0,15810.7,1.3,NaN,NaN
2024-07-01,158637.0,7910.0,313.534,263541.0,710409.0,4.3,1237.0,102.3058,16983.9,265266.0,338282.0,2168990.0,141.8,318.872,122.262,123.187,1406.0,77.4067,2565930.0,149.2,-6.6,15870.3,13.9,NaN,NaN
2024-08-01,158779.0,7673.0,314.121,289454.0,710773.0,4.2,1356.0,103.1389,17002.0,266603.0,345394.0,2162683.0,141.4,319.768,122.459,123.378,1470.0,77.9560,2574923.0,148.2,-4.7,16089.7,-7.0,NaN,NaN